<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>AsterDock.UI</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.0" />
    <PackageReference Include="Semi.Avalonia" Version="12.1.0.1" />
    <PackageReference Include="Irihi.Ursa" Version="2.2.0" />
    <PackageReference Include="Irihi.Ursa.Themes.Semi" Version="2.2.0" />
  </ItemGroup>
</Project>
