<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>DeviceInformation.Module</RootNamespace>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\AsterDock.Contracts\AsterDock.Contracts.csproj" />
    <PackageReference Include="Avalonia" Version="12.1.0" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.0" />
  </ItemGroup>
  <ItemGroup>
    <None Update="app.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
