<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>AsterDock.Host</RootNamespace>
    <AssemblyName>AsterDock.Host</AssemblyName>
    <UseAppHost>true</UseAppHost>
    <RuntimeIdentifiers>win-x64;win-arm64;osx-x64;osx-arm64</RuntimeIdentifiers>
    <BundleApplications Condition="'$(BundleApplications)' == ''">true</BundleApplications>
    <BundledModuleProject>$(MSBuildProjectDirectory)\..\InvoicePrinter.Module\InvoicePrinter.Module.csproj</BundledModuleProject>
    <BundledModuleOutput>$(MSBuildProjectDirectory)\..\InvoicePrinter.Module\bin\$(Configuration)\net10.0</BundledModuleOutput>
    <BundledDeviceModuleProject>$(MSBuildProjectDirectory)\..\DeviceInformation.Module\DeviceInformation.Module.csproj</BundledDeviceModuleProject>
    <BundledDeviceModuleOutput>$(MSBuildProjectDirectory)\..\DeviceInformation.Module\bin\$(Configuration)\net10.0</BundledDeviceModuleOutput>
    <BundledHomeModuleProject>$(MSBuildProjectDirectory)\..\Home.Module\Home.Module.csproj</BundledHomeModuleProject>
    <BundledHomeModuleOutput>$(MSBuildProjectDirectory)\..\Home.Module\bin\$(Configuration)\net10.0</BundledHomeModuleOutput>
    <BundledNetworkModuleProject>$(MSBuildProjectDirectory)\..\NetworkAccelerator.Module\NetworkAccelerator.Module.csproj</BundledNetworkModuleProject>
    <BundledNetworkModuleOutput>$(MSBuildProjectDirectory)\..\NetworkAccelerator.Module\bin\$(Configuration)\net10.0</BundledNetworkModuleOutput>
    <BundledAndroidScreenModuleProject>$(MSBuildProjectDirectory)\..\AndroidScreen.Module\AndroidScreen.Module.csproj</BundledAndroidScreenModuleProject>
    <BundledAndroidScreenModuleOutput>$(MSBuildProjectDirectory)\..\AndroidScreen.Module\bin\$(Configuration)\net10.0</BundledAndroidScreenModuleOutput>
    <BundledSerialDebuggerModuleProject>$(MSBuildProjectDirectory)\..\SerialDebugger.Module\SerialDebugger.Module.csproj</BundledSerialDebuggerModuleProject>
    <BundledSerialDebuggerModuleOutput>$(MSBuildProjectDirectory)\..\SerialDebugger.Module\bin\$(Configuration)\net10.0</BundledSerialDebuggerModuleOutput>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\AsterDock.Contracts\AsterDock.Contracts.csproj" />
    <ProjectReference Include="..\AsterDock.UI\AsterDock.UI.csproj" />
    <ProjectReference Include="..\DeviceInformation.Core\DeviceInformation.Core.csproj" />
    <ProjectReference Include="..\InvoicePrinter.Module\InvoicePrinter.Module.csproj" ReferenceOutputAssembly="false" Private="false"
                      GlobalPropertiesToRemove="RuntimeIdentifier;RuntimeIdentifiers;SelfContained;PublishSingleFile" />
    <ProjectReference Include="..\DeviceInformation.Module\DeviceInformation.Module.csproj" ReferenceOutputAssembly="false" Private="false"
                      GlobalPropertiesToRemove="RuntimeIdentifier;RuntimeIdentifiers;SelfContained;PublishSingleFile" />
    <ProjectReference Include="..\Home.Module\Home.Module.csproj" ReferenceOutputAssembly="false" Private="false"
                      GlobalPropertiesToRemove="RuntimeIdentifier;RuntimeIdentifiers;SelfContained;PublishSingleFile" />
    <ProjectReference Include="..\NetworkAccelerator.Module\NetworkAccelerator.Module.csproj" ReferenceOutputAssembly="false" Private="false"
                      GlobalPropertiesToRemove="RuntimeIdentifier;RuntimeIdentifiers;SelfContained;PublishSingleFile" />
    <ProjectReference Include="..\AndroidScreen.Module\AndroidScreen.Module.csproj" ReferenceOutputAssembly="false" Private="false"
                      GlobalPropertiesToRemove="RuntimeIdentifier;RuntimeIdentifiers;SelfContained;PublishSingleFile" />
    <ProjectReference Include="..\SerialDebugger.Module\SerialDebugger.Module.csproj" ReferenceOutputAssembly="false" Private="false"
                      GlobalPropertiesToRemove="RuntimeIdentifier;RuntimeIdentifiers;SelfContained;PublishSingleFile" />
    <PackageReference Include="Avalonia" Version="12.1.0" />
    <PackageReference Include="Avalonia.Desktop" Version="12.1.0" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.0" />
  </ItemGroup>
  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <Target Name="BuildBundledApplications" AfterTargets="Build"
          Condition="'$(DesignTimeBuild)' != 'true' and '$(BundleApplications)' == 'true'">
    <ItemGroup>
      <BundledModuleFiles Include="$(BundledModuleOutput)\**\*" />
      <BundledDeviceModuleFiles Include="$(BundledDeviceModuleOutput)\**\*" />
      <BundledHomeModuleFiles Include="$(BundledHomeModuleOutput)\**\*" />
      <BundledNetworkModuleFiles Include="$(BundledNetworkModuleOutput)\**\*" />
      <BundledAndroidScreenModuleFiles Include="$(BundledAndroidScreenModuleOutput)\**\*" />
      <BundledSerialDebuggerModuleFiles Include="$(BundledSerialDebuggerModuleOutput)\**\*" />
    </ItemGroup>
    <Copy SourceFiles="@(BundledModuleFiles)"
          DestinationFiles="@(BundledModuleFiles->'$(OutDir)Apps\InvoicePrinter\%(RecursiveDir)%(Filename)%(Extension)')"
          SkipUnchangedFiles="true" />
    <Copy SourceFiles="$(MSBuildProjectDirectory)\..\InvoicePrinter.Module\app.json"
          DestinationFolder="$(OutDir)Apps\InvoicePrinter" SkipUnchangedFiles="true" />
    <Copy SourceFiles="@(BundledDeviceModuleFiles)"
          DestinationFiles="@(BundledDeviceModuleFiles->'$(OutDir)Apps\DeviceInformation\%(RecursiveDir)%(Filename)%(Extension)')"
          SkipUnchangedFiles="true" />
    <Copy SourceFiles="$(MSBuildProjectDirectory)\..\DeviceInformation.Module\app.json"
          DestinationFolder="$(OutDir)Apps\DeviceInformation" SkipUnchangedFiles="true" />
    <Copy SourceFiles="@(BundledHomeModuleFiles)"
          DestinationFiles="@(BundledHomeModuleFiles->'$(OutDir)Apps\Home\%(RecursiveDir)%(Filename)%(Extension)')"
          SkipUnchangedFiles="true" />
    <Copy SourceFiles="$(MSBuildProjectDirectory)\..\Home.Module\app.json"
          DestinationFolder="$(OutDir)Apps\Home" SkipUnchangedFiles="true" />
    <Copy SourceFiles="@(BundledNetworkModuleFiles)"
          DestinationFiles="@(BundledNetworkModuleFiles->'$(OutDir)Apps\NetworkAccelerator\%(RecursiveDir)%(Filename)%(Extension)')"
          SkipUnchangedFiles="true" />
    <Copy SourceFiles="$(MSBuildProjectDirectory)\..\NetworkAccelerator.Module\app.json"
          DestinationFolder="$(OutDir)Apps\NetworkAccelerator" SkipUnchangedFiles="true" />
    <Copy SourceFiles="@(BundledAndroidScreenModuleFiles)"
          DestinationFiles="@(BundledAndroidScreenModuleFiles->'$(OutDir)Apps\AndroidScreen\%(RecursiveDir)%(Filename)%(Extension)')"
          SkipUnchangedFiles="true" />
    <Copy SourceFiles="$(MSBuildProjectDirectory)\..\AndroidScreen.Module\app.json"
          DestinationFolder="$(OutDir)Apps\AndroidScreen" SkipUnchangedFiles="true" />
    <Copy SourceFiles="@(BundledSerialDebuggerModuleFiles)"
          DestinationFiles="@(BundledSerialDebuggerModuleFiles->'$(OutDir)Apps\SerialDebugger\%(RecursiveDir)%(Filename)%(Extension)')"
          SkipUnchangedFiles="true" />
    <Copy SourceFiles="$(MSBuildProjectDirectory)\..\SerialDebugger.Module\app.json"
          DestinationFolder="$(OutDir)Apps\SerialDebugger" SkipUnchangedFiles="true" />
  </Target>

  <Target Name="PublishBundledApplications" AfterTargets="Publish"
          Condition="'$(DesignTimeBuild)' != 'true' and '$(BundleApplications)' == 'true'">
    <ItemGroup>
      <PublishedModuleFiles Include="$(BundledModuleOutput)\**\*" />
      <PublishedDeviceModuleFiles Include="$(BundledDeviceModuleOutput)\**\*" />
      <PublishedHomeModuleFiles Include="$(BundledHomeModuleOutput)\**\*" />
      <PublishedNetworkModuleFiles Include="$(BundledNetworkModuleOutput)\**\*" />
      <PublishedAndroidScreenModuleFiles Include="$(BundledAndroidScreenModuleOutput)\**\*" />
      <PublishedSerialDebuggerModuleFiles Include="$(BundledSerialDebuggerModuleOutput)\**\*" />
    </ItemGroup>
    <Copy SourceFiles="@(PublishedModuleFiles)"
          DestinationFiles="@(PublishedModuleFiles->'$(PublishDir)Apps\InvoicePrinter\%(RecursiveDir)%(Filename)%(Extension)')"
          SkipUnchangedFiles="true" />
    <Copy SourceFiles="$(MSBuildProjectDirectory)\..\InvoicePrinter.Module\app.json"
          DestinationFolder="$(PublishDir)Apps\InvoicePrinter" SkipUnchangedFiles="true" />
    <Copy SourceFiles="@(PublishedDeviceModuleFiles)"
          DestinationFiles="@(PublishedDeviceModuleFiles->'$(PublishDir)Apps\DeviceInformation\%(RecursiveDir)%(Filename)%(Extension)')"
          SkipUnchangedFiles="true" />
    <Copy SourceFiles="$(MSBuildProjectDirectory)\..\DeviceInformation.Module\app.json"
          DestinationFolder="$(PublishDir)Apps\DeviceInformation" SkipUnchangedFiles="true" />
    <Copy SourceFiles="@(PublishedHomeModuleFiles)"
          DestinationFiles="@(PublishedHomeModuleFiles->'$(PublishDir)Apps\Home\%(RecursiveDir)%(Filename)%(Extension)')"
          SkipUnchangedFiles="true" />
    <Copy SourceFiles="$(MSBuildProjectDirectory)\..\Home.Module\app.json"
          DestinationFolder="$(PublishDir)Apps\Home" SkipUnchangedFiles="true" />
    <Copy SourceFiles="@(PublishedNetworkModuleFiles)"
          DestinationFiles="@(PublishedNetworkModuleFiles->'$(PublishDir)Apps\NetworkAccelerator\%(RecursiveDir)%(Filename)%(Extension)')"
          SkipUnchangedFiles="true" />
    <Copy SourceFiles="$(MSBuildProjectDirectory)\..\NetworkAccelerator.Module\app.json"
          DestinationFolder="$(PublishDir)Apps\NetworkAccelerator" SkipUnchangedFiles="true" />
    <Copy SourceFiles="@(PublishedAndroidScreenModuleFiles)"
          DestinationFiles="@(PublishedAndroidScreenModuleFiles->'$(PublishDir)Apps\AndroidScreen\%(RecursiveDir)%(Filename)%(Extension)')"
          SkipUnchangedFiles="true" />
    <Copy SourceFiles="$(MSBuildProjectDirectory)\..\AndroidScreen.Module\app.json"
          DestinationFolder="$(PublishDir)Apps\AndroidScreen" SkipUnchangedFiles="true" />
    <Copy SourceFiles="@(PublishedSerialDebuggerModuleFiles)"
          DestinationFiles="@(PublishedSerialDebuggerModuleFiles->'$(PublishDir)Apps\SerialDebugger\%(RecursiveDir)%(Filename)%(Extension)')"
          SkipUnchangedFiles="true" />
    <Copy SourceFiles="$(MSBuildProjectDirectory)\..\SerialDebugger.Module\app.json"
          DestinationFolder="$(PublishDir)Apps\SerialDebugger" SkipUnchangedFiles="true" />
  </Target>
</Project>
