<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>InvoicePrinter.Core</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="PDFtoImage" Version="5.2.1" />
    <PackageReference Include="SkiaSharp" Version="3.119.2" />
  </ItemGroup>
</Project>
